#!/bin/bash

stop=0
while [ $stop -eq 0 ]
do
    cat << ENDOFMENU
    1  : print the date.
    2,3: print current working directory.
    4  : exit
ENDOFMENU
    echo -n "Your choice? "
    read reply
    echo
    case $reply in
        "1")
            date
            ;;
        "2"|"3")
            pwd
            ;;
        "4")
            stop=1
            ;;
        *)
            echo illegal choice
            ;;
    esac
done
